---
- hosts: localhost

  tasks:

    - name: check that GET method works ok!
      uri:
        url: http://35.198.4.192:5000/customers
        method: POST
        body: "id=4&name=My New Customer again"
        status_code: 302
